### PR TITLE
Fix broken links in status section of README.md

### PR DESCRIPTION
**Pull request by jonathanmanton**

### CODE REVIEW

**Comment by jonathanmanton** [comment]
My first pull request ever for any project.  Please be gentle.  :-)

**Review by yxxhero — APPROVED** [review]

**Comment by yxxhero** [comment]
Please fix DCO

**Comment by yxxhero** [comment]
@jonathanmanton see: https://github.com/helmfile/helmfile/pull/1618/checks?check_run_id=27189591187

**Comment by jonathanmanton** [comment]
> @jonathanmanton see: https://github.com/helmfile/helmfile/pull/1618/checks?check_run_id=27189591187

I cannot follow these instructions.  It asks me to check out the pull request (`gh pr checkout 1618`).  If I do this in a local copy of the `helmfile/helmfile` repository, it (mostly) works (there is no `HEAD-3` branch), but when I take the steps requested I get an HTTP 403 error on the push because I (rightly) do not have access to write to that repository.  If I try to do this in my repository (`jonathanmanton/helmfile`), it does not recognize the pull request checkout, since the pull request is in the `helmfile/helmfile` repository, not in my fork. 

I'll use this as an opportunity to learn more about rebasing commits.  If I can't figure it out in an hour or so I may just delete this pull request and create a new one that has the commit properly signed in the first place.

**Comment by jonathanmanton** [comment]
Looks like my eyes are getting old.  `HEAD~3` and `HEAD-3` are not equivalent...  Hopefully will be fixed now.

**Comment by yxxhero** [comment]
@jonathanmanton fixed. thanks so much.

**Review by yxxhero — APPROVED** [review]

**Pull request merged**
