### PR TITLE
feat: add friendly tips for helmfile config order

### PR DESCRIPTION
**Pull request by yxxhero**
feat: add kindful tips for helmfile config order.

check `bases` `environments` `releases` key order. And show more friendly tips.

### CODE REVIEW

**Comment by xiaomudk** [comment]
Great job!
I think the code can be simplified, here is my description of my ideas in python:
```
#!/bin/python3
topkeysPriority = {
	"bases": 0,
	"environments": 1,
	"releases": 2
}

def check(keys):
	if len(keys) == 1:
		return True

	for i in range(1, len(keys)):
		key1 = topkeysPriority[keys[i-1]]
		key2 = topkeysPriority[keys[i]]
		if key1 >= key2:
			return False
	return True

print(check(['bases']))
print(check(['bases', 'releases']))
print(check(['bases','environments' ,'releases']))
print(check(['environments', 'bases']))
print(check(['bases', 'bases']))
print(check(['releases', 'bases']))
        
```

**Review by xiaomudk — APPROVED** [review]

**Comment by mumoshu** [comment]
@yxxhero Hey! Would you mind clarifying why you need this? Since Helmfile v1 we are going to force `environments` and `releases` to be in separate helmfile.yaml parts via `---` so there should be no need to force a specific key order at least for helmfile v1.
Also, this seems like a backward incompatible change. Can we turn this on only for v1, or make it just a warning(don't force-exit helmfile) for v0?

**Comment by yxxhero** [comment]
@mumoshu thanks for your option. let me show an example:
```
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: test
    chart: bitnami/nginx
    namespace: {{ .Values.ns }}
---
environments:
  default:
    values:
      - ns: test2
```
it will has errors.
```
err: error during a.yaml.gotmpl.part.0 parsing: template: stringTemplate:7:25: executing "stringTemplate" at <.Values.ns>: map has no entry for key "ns"
changing working directory back to "/root"
in ./a.yaml.gotmpl: error during a.yaml.gotmpl.part.0 parsing: template: stringTemplate:7:25: executing "stringTemplate" at <.Values.ns>: map has no entry for key "ns"
```

if we change the helmfile to the below:
```
environments:
  default:
    values:
      - ns: test2
---
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: test
    chart: bitnami/nginx
    namespace: {{ .Values.ns }}
```
all is ok.


So I think we should add the tips for the helmfile uses. reduce some of the confusion.


/cc @mumoshu

**Comment by mumoshu** [comment]
@yxxhero Ah, that makes sense! Thanks for clarifying.
Could you also somehow make this warning to be emitted only when there's `---` in-between?

I think this is ok-ish in v0 and not allowed in v1:

```
releases:
  - name: test
    chart: bitnami/nginx
    namespace: {{ .Values.ns }}

environments:
  default:
    values:
      - ns: test2
```

while this is wrong in both v0 and v1:

 ```
releases:
  - name: test
    chart: bitnami/nginx
    namespace: {{ .Values.ns }}

---

environments:
  default:
    values:
      - ns: test2
```

If you could somehow differentiate the above 2 cases in code and emit a warning only for the latter case, it looks perfect.

**Comment by yxxhero** [comment]
@mumoshu ok. I will update code.

**Comment by yxxhero** [comment]
@mumoshu warn in v0, error in v1.

**Review by xiaomudk — APPROVED** [review]

**Pull request merged**
