### PR TITLE
rename execEnvs to envExec

### PR DESCRIPTION
**Pull request by yxxhero**
Signed-off-by: yxxhero <aiopsclub@163.com>

rename execEnvs to envExec

### CODE REVIEW

**Review by itscaro — APPROVED** [review]

**Comment by itscaro** [comment]
@yxxhero Could you explain the reason in the PR description?

**Comment by yxxhero** [comment]
@itscaro see https://github.com/helmfile/helmfile/pull/95#discussion_r874255528

**Comment by yxxhero** [comment]
@itscaro Thanks very much.

**Comment by yxxhero** [comment]
@itscaro This first arg of `EnvExec` should be map[string]interface{}. Go template pass map[string]interface{} into `EnvExec`.
I will add e2e test for tmpl funcs.

**Comment by yxxhero** [comment]
@itscaro ping

**Comment by yxxhero** [comment]
@itscaro ping   Thanks very much.

**Comment by yxxhero** [comment]
@mumoshu ping

**Pull request merged**
