### PR TITLE
fix: needs logic in chart stage

### PR DESCRIPTION
**Pull request by yxxhero**
Signed-off-by: yxxhero <aiopsclub@163.com>

fix: fix needs logic in chart stage

### CODE REVIEW

**Comment by yxxhero** [comment]
@mumoshu @itscaro

**Comment by mumoshu** [comment]
@yxxhero Thanks for fixing those! Would you also mind adding some integration test cases so that we won't break anything in the future and we are sure what this fixes?

**Comment by yxxhero** [comment]
Ok. I will do later.

**Comment by yxxhero** [comment]
@mumoshu

**Comment by yxxhero** [comment]
done

**Review by itscaro — APPROVED** [review]
LGTM

**Pull request merged**
