### PR TITLE
chore: update vals to v0.17.1

### PR DESCRIPTION
**Pull request by philomory**
Updates `vals` to v0.17.1 to get access to the new providers and features, including:
* `sops` provider Base64 encoding
* `vault` provider namespace support
* `envsubst` provider
* `awskms` provider

### CODE REVIEW

**Comment by yxxhero** [comment]
@philomory Please fix DCO issue.

**Comment by philomory** [comment]
@yxxhero DCO issue fixed!

**Review by yxxhero — DISMISSED** [review]

**Comment by yxxhero** [comment]
This branch has conflicts that must be resolved

**Comment by philomory** [comment]
It probably needs to be rebased after the merging of some other pull requests; though, if you like we could close this one in favor of #152 from dependabot.

**Comment by philomory** [comment]
OK, I rebased and re-ran `go mod tidy` to regenerate `go.sum`, but, as I said, we could also just switch to Dependabot's probably-equivalent PR.

**Comment by yxxhero** [comment]
@philomory Ok. I will this PR. Thanks very much. I hope you can continue to participate. best wishes to you.

**Pull request closed without merging**
