### PR TITLE
Add --wait flag into destroy/delete commands

### PR DESCRIPTION
**Pull request by virginiabrioso**
I noticed that when using wait: true the flag "--wait" was only being implemented in the sync/apply commands, this commit is to extend this to the destroy/delete commands

Usage:

`helmfile destroy` together with

```
helmDefaults:
  wait: true
```

Related to https://github.com/helmfile/helmfile/issues/1057

### CODE REVIEW

**Comment by yxxhero** [comment]
@virginiabrioso  please fix DCO issue. follow the link: https://github.com/helmfile/helmfile/pull/1080/checks?check_run_id=17841444835

**Comment by virginiabrioso** [comment]
> @virginiabrioso please fix DCO issue. follow the link: https://github.com/helmfile/helmfile/pull/1080/checks?check_run_id=17841444835

Hello! I just updated it

**Comment by felipecrs** [comment]
We actually found a problem with this implementation. When running `helm delete --wait`, it will wait for as long as `--timeout`, which defaults to 5 minutes. Depending on how the helm charts are coded (some can have pre or post uninstall hooks that can take several minutes to complete), they can fail during the uninstallation due to timeout.

The only way around it that I can imagine is to introduce a new flag: `deleteTimeout` where you can specify the amount of time to pass for `--timeout` when `wait: true` for the `helm delete` command.

But if we go that route, why not also separate the `wait` flag, one for sync and another for destroy like `deleteWait`?

**Comment by yxxhero** [comment]
@felipecrs make sense.

**Comment by felipecrs** [comment]
So, @yxxhero, are you okay with the proposal of adding the `deleteWait` and `deleteTimeout` options?

**Comment by felipecrs** [comment]
Please keep this open

**Pull request closed without merging**
