### PR TITLE
add xiaomudk as maintainer

### PR DESCRIPTION
**Pull request by yxxhero**
Signed-off-by: yxxhero <aiopsclub@163.com>

@mumoshu
@itscaro 
 

I would like to recommend a friend to join helmfile. He is involved in many open-source projects and has rich experience in software development. We can work together to maintain helmfile.  What’s you opinion? https://github.com/helmfile/helmfile/commits?author=xiaomudk

Recent Work: helmfile init

### CODE REVIEW

**Review by itscaro — APPROVED** [review]

**Comment by yxxhero** [comment]
@mumoshu WDYT? Thanks very much.

**Comment by mumoshu** [comment]
Let's include https://github.com/helmfile/helmfile/pull/520 as @xiaomudk's recent big contribution!

**Comment by yxxhero** [comment]
@xiaomudk good work. Thanks very much.

> Let's include #520 as @xiaomudk's recent big contribution!

@xiaomudk good work. Thanks very much.

**Comment by yxxhero** [comment]
@xiaomudk great job: https://github.com/helmfile/helmfile/pull/522

**Review by mumoshu — APPROVED** [review]
Welcome @xiaomudk!

**Comment by yxxhero** [comment]
@mumoshu maybe we need to invite @xiaomudk to join the `helmfile` org.

**Comment by xiaomudk** [comment]
@mumoshu @yxxhero Thank you very much, reliable partners!

**Pull request merged**
