### PR TITLE
reconstruct main function

### PR DESCRIPTION
**Pull request by yxxhero**
Signed-off-by: yxxhero <aiopsclub@163.com>

reconstruct main function

https://github.com/helmfile/helmfile/discussions/82

### CODE REVIEW

**Comment by yxxhero** [comment]
@itscaro
@mumoshu  ping

**Review by mumoshu — COMMENTED** [review]
@yxxhero Hey. Thanks for your contribution as always! As I have suggested in Slack, I'd appreciate it if you could start by extracting only one command in the first pr, so that it is more reviewable.

**Comment by yxxhero** [comment]
@mumoshu ok. I will change this.

**Comment by yxxhero** [comment]
@mumoshu done. Please review. Thanks very much.

**Comment by yxxhero** [comment]
@mumoshu @itscaro ping

**Review by mumoshu — APPROVED** [review]
LGTM. Thanks a lot for your contribution!

**Pull request merged**
