### PR TITLE
Fix NewFileRenderer args along with testfs for mocking ReadDir in tests

### PR DESCRIPTION
**Pull request by mumoshu**
Follow-up for #297
Ref https://github.com/helmfile/helmfile/pull/297#issuecomment-1217609669

I believe I need to update a few more places in the code like StateCreator, DesiredStateLoader and so on. So, this needs a bit more work and manual testing before getting merged.

### CODE REVIEW

**Comment by arkaitzj** [comment]
Hi @mumoshu, I have a patch half-done on this. 
It looks like the number of asbtracted fs functions is growing so I thought about abstracting all on a filesystem struct and pass a single *fs around instead of all those functions.
Its half done because there are a ton of places where there are fs function pointers passed so it would take me more time to work on it. Please let me know if I should drop it.

**Comment by mumoshu** [comment]
@arkaitzj Hey! Thanks a lot for your effort and support ❤️ 

> I thought about abstracting all on a filesystem struct and pass a single *fs around instead of all those functions.

That's the way to go! Yeah so we have many constructor functions and structs that accepts varying combinations of readFile, readDir, fileExists, etc. It should be wrapped in a filesystem abstraction, something that implements all the https://pkg.go.dev/io/fs#ReadDirFS, https://pkg.go.dev/io/fs#ReadFileFS, https://pkg.go.dev/io/fs#StatFS, and https://pkg.go.dev/io/fs#GlobFS.

> Its half done because there are a ton of places where there are fs function pointers passed so it would take me more time to work on it. Please let me know if I should drop it.

Thanks for sharing and the suggestion!
I'd really appreciate it if you could submit a pull request for your work too, so that we can compare the two (or more upcoming work related to this), collect issues and ideas, and eventually settle to a complete work!

**Comment by arkaitzj** [comment]
@mumoshu working on this branch: https://github.com/helmfile/helmfile/pull/307

**Comment by mumoshu** [comment]
Closing in favor of #307
Thanks a lot for your contribution @arkaitzj!

**Pull request closed without merging**
