### PR TITLE
Bump Go to 1.20

### PR DESCRIPTION
**Pull request by yxxhero**
Signed-off-by: yxxhero <aiopsclub@163.com>

bump go 1.20

### CODE REVIEW

**Comment by yxxhero** [comment]
see: https://github.com/golang/go/issues/53261

**Comment by yxxhero** [comment]
```
ext/template/parse: simplify I/O in lexing

The concurrent model for delivering tokens was fine for pedagogy,
but has caused a few problems as the package has evolved (that is,
got more complicated). It's easy to eliminate it, simplifying or
removing some of the hacks used to work around these prolems.

The old lexer would deliver tokens over a channel to the parsing
goroutine, and continue running until EOF. In this rewrite, we
instead run the machine until a token is ready, and shut it down
until the next token is needed. The mechanism is just to return nil
as the state function, which requires a bit more threading of return
values through the state functions but is not difficult. The change
is modest.

A couple of error messages change, but otherwise the change has no
external effect. This is just an internal cleanup, long overdue.

benchmark                      old ns/op     new ns/op     delta
BenchmarkParseLarge-20         12222729      6769966       -44.61%
BenchmarkVariableString-20     73.5          73.4          -0.16%
BenchmarkListString-20         1827          1841          +0.77%

benchmark                      old allocs     new allocs     delta
BenchmarkVariableString-20     3              3              +0.00%
BenchmarkListString-20         31             31             +0.00%

benchmark                      old bytes     new bytes     delta
BenchmarkVariableString-20     72            72            +0.00%
BenchmarkListString-20         1473          1473          +0.00%
```

**Comment by xiaomudk** [comment]
I think it is necessary to note the discussion that golangci-lint supports golang 1.20： https://github.com/golangci/golangci-lint/pull/3414
> Note for GitHub Action users: the Go version must be quoted ('1.20') otherwise it is interpreted as a float (1.2).

**Review by xiaomudk — APPROVED** [review]

**Review by mumoshu — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
