### PR TITLE
chore: bump variantdev/vals to support remote secret tfstateremote

### PR DESCRIPTION
**Pull request by carnei-ro**

### CODE REVIEW

**Comment by carnei-ro** [comment]
Tests are failing because of the cache :\

**Comment by mumoshu** [comment]
@carnei-ro go's dependency resolution should work agnostic to the existence of cache 🤔 Perhaps it makes difference if you ran ` go mod tidy` with go 1.18 and update the pr with the changes?

**Comment by carnei-ro** [comment]
@mumoshu would you approve again, pls?

**Comment by carnei-ro** [comment]
@mumoshu @itscaro I've run `go mod tidy` to check if the test will pass. Would you approve again, pls?

**Pull request merged**
