### PR TITLE
add Go lint

### PR DESCRIPTION
**Pull request by yxxhero**
Signed-off-by: yxxhero <aiopsclub@163.com>

add Go lint

### CODE REVIEW

**Comment by mumoshu** [comment]
@yxxhero Hey! Thanks for your contribution as always.

I see it emits a lot of lint errors. Perhaps we’d merge it and start submitting PRs to fix each lint error, or start with disabling failing sub-linters, and submit follow-up PRs to fix each group of errors while enabling the linter one-by-one?
My personal preference is the latter, but I'm also interested in your thought.

**Comment by yxxhero** [comment]
@mumoshu I agree with you. I will do this laster. Thanks very much.

**Comment by yxxhero** [comment]
@mumoshu ping

**Comment by yxxhero** [comment]
@mumoshu I fix for the new code.

**Comment by mumoshu** [comment]
@yxxhero Thanks 🙏 Really looking forward to get this merged!

**Comment by yxxhero** [comment]
@mumoshu ready to review.

**Review by mumoshu — APPROVED** [review]
LGTM. Thanks a lot for your efforts!

**Comment by mumoshu** [comment]
@yxxhero You can merge this once CI passes!

**Comment by yxxhero** [comment]
@mumoshu yes. Thanks very much.

**Pull request merged**
