### PR TITLE
[#80] README, update release tag url

### PR DESCRIPTION
**Pull request by yjqg6666**
Update to the latest release tag v0.143.4.

### CODE REVIEW

**Comment by yxxhero** [comment]
@yjqg6666 Please fix DCO issue. Thanks very much.

**Comment by yjqg6666** [comment]
@yxxhero fixed.

**Review by itscaro — APPROVED** [review]

**Review by jeremyshor — CHANGES_REQUESTED** [review]
Can we update the Installation/Running as a contiainer sections as well?
 * Line 401 refers to the old roboll repo. Current helmfile/helmfile repo has no releases. What is the current equivalent to these releases?
 * Line 410 refers to quay.io/roboll/helmfile which is the old repo. Can we get this updated too?

**Comment by yjqg6666** [comment]
@JShorRR Line 401 updated. Line 410 for docker image, I havn't found quay.io/helmfile/helmfile or hub.docker.com/helmfile/helmfile and images at quay.io/roboll/helmfile have still been updated/uploaded.

**Review by JShorRR — APPROVED** [review]

**Pull request merged**
