### PR TITLE
Fix --skip-needs regression introduced in v0.145.0

### PR DESCRIPTION
**Pull request by yxxhero**
Signed-off-by: yxxhero <aiopsclub@163.com>

fix --skip-needs issue

fixed: https://github.com/helmfile/helmfile/issues/339

### CODE REVIEW

**Comment by stek29** [comment]
@mumoshu @itscaro PTAL :)

**Comment by yxxhero** [comment]
@stek29 do you meet this?

**Comment by stek29** [comment]
@yxxhero well I'm waiting for next release with `list` speedup, and it's blocked by this PR, so yes

**Comment by yxxhero** [comment]
@yxxhero yeah. when this Pr is merged. we will create a new release. Thanks very much. thanks for your works. looking forword your more and more work for helmfile.

**Comment by yxxhero** [comment]
@mumoshu done. sorry for this issue.

**Comment by yxxhero** [comment]
@mumoshu and this is ok.

**Review by mumoshu — APPROVED** [review]
LGTM. Thanks for fixing it!!

**Comment by yxxhero** [comment]
@stek29 enjoy 0.145.5. Thanks very much.

**Pull request merged**
