### PR TITLE
resolved deps even when installed=false

### LINKED ISSUE #1119: in ./helmfile.yaml: unable to update deps: no resolved dependency found for "tetragon", running "helmfile deps" may resolve the issue
### Operating system

ubuntu

### Helmfile Version

the exact commit is 212c39cb533876eb87b083c2c6cc909ad7b8664c

### Helm Version

-

### Bug description

when I run helmfile deps and there are releases with installed: false, it fails with :

``` 
in ./helmfile.yaml: unable to update deps: no resolved dependency found for "tetragon", running "helmfile deps" may resolve the issue
```

using git bisect, I found the issue is introduced by https://github.com/helmfile/helmfile/pull/1054 

### Example helmfile.yaml

```
releases:
  - chart: cilium/tetragon
    name: tetragon
    namespace: kube-system
    installed: false
    values:
      - tetragon.yaml
```

### Error message you've seen (if any)

in ./helmfile.yaml: unable to update deps: no resolved dependency found for "tetragon", running "helmfile deps" may resolve the issue

### Steps to reproduce

-

### Working Helmfile Version

latest commit working : d5a6553664b7797f54d985fd91d9e5290a7d45a6

### Relevant discussion

_No response_

### PR DESCRIPTION
**Pull request by jouve**
fix #1119
revert #1054

### CODE REVIEW

**Comment by xiaomudk** [comment]
@yxxhero need your advice.

**Comment by yxxhero** [comment]
@mumoshu WDYT?

**Comment by jouve** [comment]
regardless of the error described here, I think that if the release is part of helmfile state (regarless of installed), it should be part of the helmfile.lock

**Comment by mumoshu** [comment]
Good catch! But then we are back to #1053... Can we somehow resolve both?

How about fixing #1054 so that you do skip deps also on `helmfile deps` not only other helmfile commands that imply `deps`? @yxxhero 

> it should be part of the helmfile.lock

I can understand that it might be more natural! However, from a practical perspective, there's no actual use for the not-installed dependency within the helmfile.lock, no?

@jouve If we could make it `helmfile deps` work on your setup, without reverting #1054, would that be fine for you?

**Comment by yxxhero** [comment]
> Good catch! But then we are back to #1053... Can we somehow resolve both?
> 
> How about fixing #1054 so that you do skip deps also on `helmfile deps` not only other helmfile commands that imply `deps`? @yxxhero
> 
> > it should be part of the helmfile.lock
> 
> I can understand that it might be more natural! However, from a practical perspective, there's no actual use for the not-installed dependency within the helmfile.lock, no?
> 
> @jouve If we could make it `helmfile deps` work on your setup, without reverting #1054, would that be fine for you?

make sense.

**Comment by yxxhero** [comment]
@jouve yeah. we should find a better method to solve all the issues. WDYT? I can help you.

**Comment by yxxhero** [comment]
@jouve @xiaomudk @mumoshu I will merge this PR. and find a better way to solve https://github.com/helmfile/helmfile/pull/1054

**Review by yxxhero — APPROVED** [review]

**Pull request merged**
