### PR TITLE
Add proposals about two breaking changes before we cut Helmfile 1.0

### PR DESCRIPTION
**Pull request by mumoshu**
@itscaro @yxxhero I have some ideas about how we proceed to 1.0. WDYT?

// BTW, once we reach 1.0, I have an idea to make the user experience of writing and reading helmfile configs more great, by using Starlark as the basis for Helmfile config syntax 😃 Following the policy described in this proposal, it will be added as a secondary config syntax and we'll keep current yaml+gotemplate based syntax as is, at least while in 1.x.

### CODE REVIEW

**Comment by yxxhero** [comment]
@mumoshu It's very good. I like those ideas.

**Review by yxxhero — APPROVED** [review]
/LGTM

**Comment by yxxhero** [comment]
@mumoshu The project introduces many closure logic and functions as parameters, which is not easy to read. WDYT?

**Comment by mumoshu** [comment]
@yxxhero We can defer any major refactorings to post-1.0 as long as they don't incur breaking changes(and they shouldn't) but anyway, do you have any better ideas? Closures are used as a way to consistently apply all the pre/post conditions to the main logic for each helmfile sub-command. My take was that they're there for reasons, but I'm definitely open to ideas for improvements!

**Comment by yxxhero** [comment]
@mumoshu That's it for now. It will be optimized in the future

**Comment by yxxhero** [comment]
@mumoshu What is the detailed plan for 1.0, and what part can I participate in

**Pull request merged**
