### PR TITLE
feat: Auto-detect term for coloring helm-diff output

### PR DESCRIPTION
**Pull request by mumoshu**
Since helm-diff has added an ability to auto-detect the term to decide if it should output with color or not, helmfile had been defaulted to no-color.
This resoloves that, by adding a term-detection logic that is same as helm-diff.

As a part of this work, I have also implemented a new global flag `--color`, which is used for forcing color without relying on the term-detection logic implemented in helmfile or explicitly setting the HELM_DIFF_COLOR envvar. I hope it is useful for folks.

Ref https://github.com/roboll/helmfile/issues/2043

### CODE REVIEW

**Comment by itscaro** [comment]
I would like to have an exclusive validation on `--color` and `--no-color`, what do you think?

**Comment by mumoshu** [comment]
@itscaro Sounds good!

**Comment by mumoshu** [comment]
@itscaro Reread the codebase and it's a bit harder than I thought because there seems no right place to add an exclusiveness validation.

The functions like `Color` and `NoColor` in `configImpl` lacks an `error` return value so we need all those instances in the app and the test code.

Or perhaps there's maybe a better place to put such validation? Perhaps immediately before initializing App or Run structs? 🤔 

WDYT?

**Comment by itscaro** [comment]
Yes we can do some validation before initializing app, maybe around here https://github.com/helmfile/helmfile/blob/f1a250c/main.go#L996-L1011

**Comment by mumoshu** [comment]
@itscaro Added [f84ab66](https://github.com/helmfile/helmfile/pull/24/commits/f84ab66ba0208a7cdfb37e6a9aff1b7dcc3fd5c4) and manually tested it. It seems to be working!

**Pull request merged**
