### PR TITLE
feat: remove deprecated args and cmd for v1.0.0

### PR DESCRIPTION
**Pull request by yxxhero**
Signed-off-by: yxxhero <aiopsclub@163.com>

remove deprecated args and cmd

TODO:
- [ ] update documents

### CODE REVIEW

**Comment by mumoshu** [comment]
@yxxhero As discussed in Slack, can we move this behind a feature flag = envvar that is named like `HELMFILE_V1_MODE` so that we don't need to maintain two branches (0.x and 1.x) for undefined period, and testing differences between v1 and v0.x is easier as we can selectively turn on v1 mode in the same test that runs v0.x test, etc?

**Comment by mumoshu** [comment]
Instead of the envvar, we might alternatively use a build tag (maybe specify the `v1` build tag only when you want to enable v1 behavior?). Which method would you prefer?

**Comment by yxxhero** [comment]
@mumoshu It's up to you. I follow you. Thanks very much.

**Comment by mumoshu** [comment]
@yxxhero Can we safely close this as we've already merged https://github.com/helmfile/helmfile/pull/598?

**Comment by yxxhero** [comment]
@mumoshu we need to remove more code for deprecated args and cmd. WDYT?

**Comment by mumoshu** [comment]
@yxxhero I believe so! It's not now though., right? To repeat code deletions done in this PR, we need to fully remove the deprecated features. But we can't do that until we finally stop maintaining helmfile v0.x.

**Comment by yxxhero** [comment]
@mumoshu I think so. so this PR can't be merged until v1.0. but we can do this PR before v1.0.

**Comment by mumoshu** [comment]
@yxxhero I agree with you! But keeping this up-to-date with the main branch and fixing merge conflicts so often might be tiresome, right?
Can we perhaps do better, by turning this into a pull request that adds a code comment saying `// TODO: Remove this function once Helmfile v0.x reaches EOL` to every function you removed in this PR, instead of removing the function code itself?
That way, we can merge this ASAP, leaving no toil to keep this up-to-date, and it's still super easy to remove all the related code once Helmfile v0.x is EOLed, because we can just search for everything commented with the TODO thing for removal.
WDYT?

**Comment by yxxhero** [comment]
@mumoshu yeah. good idea. I will do that.

**Comment by yxxhero** [comment]
see: https://github.com/helmfile/helmfile/pull/628

**Pull request closed without merging**
