### PR TITLE
fix: use finer-grained locking when listing releases for diff

### PR DESCRIPTION
**Pull request by steved**
`isReleaseInstalled` will call `helm list` which can take a bit of time. in order to allow parallelism, we need to use a finer mutex lock.

### CODE REVIEW

**Comment by yxxhero** [comment]
@steved Please fic DCO

**Comment by yxxhero** [comment]
@steved what's benifits when this PR be merged? thanks so much.

**Review by yxxhero — APPROVED** [review]

**Comment by steved** [comment]
This really only becomes a problem with larger sets of releases, but with `--skip-diff-on-install` each release will be checked serially:

```
$ time ~/src/helmfile/helmfile apply --concurrency 4 --skip-deps --skip-diff-on-install
Listing releases matching ^sleep3$
Listing releases matching ^sleep2$
Listing releases matching ^sleep$
Listing releases matching ^sleep1$
sleep3	default  	12      	2024-02-13 15:46:46.306856 -0800 PST	deployed	sleep-0.0.0	0.0.0

sleep1	default  	12      	2024-02-13 15:46:46.305619 -0800 PST	deployed	sleep-0.0.0	0.0.0

sleep2	default  	12      	2024-02-13 15:46:46.303212 -0800 PST	deployed	sleep-0.0.0	0.0.0

sleep	default  	12      	2024-02-13 15:46:46.303146 -0800 PST	deployed	sleep-0.0.0	0.0.0

Comparing release=sleep, chart=sleep/
Comparing release=sleep1, chart=sleep/
Comparing release=sleep2, chart=sleep/
Comparing release=sleep3, chart=sleep/

real	0m1.456s
user	0m3.753s
sys	0m0.623s

$ helmfile --version && time helmfile apply --concurrency 4 --skip-deps --skip-diff-on-install
helmfile version 0.154.0
Listing releases matching ^sleep2$
sleep2	default  	12      	2024-02-13 15:46:46.303212 -0800 PST	deployed	sleep-0.0.0	0.0.0

Listing releases matching ^sleep$
sleep	default  	12      	2024-02-13 15:46:46.303146 -0800 PST	deployed	sleep-0.0.0	0.0.0

Listing releases matching ^sleep1$
sleep1	default  	12      	2024-02-13 15:46:46.305619 -0800 PST	deployed	sleep-0.0.0	0.0.0

Listing releases matching ^sleep3$
sleep3	default  	12      	2024-02-13 15:46:46.306856 -0800 PST	deployed	sleep-0.0.0	0.0.0

Comparing release=sleep, chart=sleep/
Comparing release=sleep1, chart=sleep/
Comparing release=sleep2, chart=sleep/
Comparing release=sleep3, chart=sleep/

real	0m1.392s
user	0m3.709s
sys	0m0.478s
```

**Comment by yxxhero** [comment]
@steved got it. thanks so much.

**Pull request merged**
