### PR TITLE
Refactor 'images' workflow, include Ubuntu image to push

### PR DESCRIPTION
**Pull request by pathob**
Until now, the 'images' workflow was separated into two different jobs,
one for just building the images in e.g. pull requests and the other
one for building and pushing the images e.g. after a merge to the 'main'
branch, which resulted in code repetitions. Also, both jobs used
different approaches, one (build) using a 'matrix strategy' based on
the file name of the Dockerfile, the other one (build and push) having a
seperate build and push step for each Dockerfile.

With this change, both jobs have been unified into a single "build and
optionally push" job to remove the repetitions, which now also shares
the same approach - a matrix strategy based on the file names of the
Dockerfiles.

The package naming now follows a clear schema based on the file name of
the Dockerfile. 'Dockerfile' will result in a 'helmfile' package,
'Dockerfile.ubuntu' will result in a 'helmfile-ubuntu' package and so
on. In order to keep the 'helmfile-debian-stable-slim' image package
name, the 'Dockerfile.debian' had to be renamed to
'Dockerfile.debian-stable-slim' accordingly.

Furthermore, the evaluation of the condition whether a push is intended
(or not) has been moved directly to the 'push' flag of the
'docker/build-push-action'.

### CODE REVIEW

**Comment by pathob** [comment]
This PR is the result of https://github.com/helmfile/helmfile/discussions/261

You can have a look on the new workflow in action in my fork:

- [Pull Request](https://github.com/pathob/helmfile/actions/runs/2760674062)
- [Merge to main](https://github.com/pathob/helmfile/actions/runs/2760773873)
- [Tag push](https://github.com/pathob/helmfile/actions/runs/2760835524)

The resulting packages can be found here: https://github.com/pathob?tab=packages&repo_name=helmfile

**Comment by yxxhero** [comment]
@pathob please fix DCO issue.

**Comment by pathob** [comment]
@yxxhero Now done

**Comment by yxxhero** [comment]
@pathob The default helmfile image is base of Dockerfile. It is diffrent ago. is right?

**Comment by pathob** [comment]
> @pathob The default helmfile image is base of Dockerfile. It is diffrent ago. is right?

@yxxhero Sorry, I don't understand your question, can you explain again what you mean?

**Comment by yxxhero** [comment]
@pathob The default helmfile is based on dockerfile, which is different from the previous logic.

**Comment by pathob** [comment]
Before, it was like this:

```
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and Push (debian stable-slim)
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.debian
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-debian-stable-slim:${{ steps.vars.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
```

So, `Dockerfile` was used to build `ghcr.io/helmfile/helmfile` and `Dockerfile.debian` was used to build `ghcr.io/helmfile/helmfile-debian-stable-slim`.

Now, it is like this (based on the suffix of the Dockerfile itself:

```
      - name: Build / Push
        uses: docker/build-push-action@v3
        with:
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
          tags: |
            ghcr.io/${{ github.repository }}${{ steps.vars.outputs.suffix }}:${{ steps.vars.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
```

So, `Dockerfile` is still used to build `ghcr.io/helmfile/helmfile`. But now, `Dockerfile.debian` is used to build `ghcr.io/helmfile/helmfile-debian`. And new, `Dockerfile.ubuntu` is used to build `ghcr.io/helmfile/helmfile-debian`.

For the `Dockerfile` and the `helmfile` package, nothing changed.

**Comment by yxxhero** [comment]
@pathob Thanks for your reply. is it better to build the same image name as before for `Dockerfile.debian`? WDYT? @mumoshu

**Comment by pathob** [comment]
Btw. it would also be possible to rename the `Dockerfile.debian` to `Dockerfile.debian-stable-slim` to keep the old image name.

**Comment by yxxhero** [comment]
@pathob ok. you are right.

**Comment by mumoshu** [comment]
@pathob Hey! Thanks for your efforts. This LGTM overall. One thing though- I do prefer keeping the old image name for compatibility so it would be great if you could rename the existing dockerfile to `Dockerfile.debian-stable-slim` so that (I believe) the image name is retained.
Can you fix it in this PR?

**Comment by pathob** [comment]
@mumoshu @yxxhero I've adjusted it now and renamed the file

**Comment by yxxhero** [comment]
@pathob Thanks very much. Please fix ci error.

**Comment by pathob** [comment]
@yxxhero Overlooked something, now it should work

**Comment by yxxhero** [comment]
@pathob I think Dockerfile.ubuntu should be renamed too. Thanks very much.

**Comment by mumoshu** [comment]
@yxxhero What's your preference? `Dockerfile.ubuntu-20.04`?

**Comment by yxxhero** [comment]
@mumoshu maybe Dockerfile.ubuntu-stable-slim ? same behave as Dockerfile.debian-stable-slim. right?

**Comment by pathob** [comment]
I find this "stable-slim" very uncommon, especially because it's a package (image) name. Usually this kind of stuff is handled via tags.

**Comment by yxxhero** [comment]
@pathob I agree. WDYT?

**Comment by mumoshu** [comment]
@pathob @yxxhero Hey! Thanks- I hear you, and I do believe having image variant names in the image tags is more common.

However, I prefer making the variant name a part of the image name so that it's more rennovate/dependabot friendly- AFAIK those solutions don't support filtering image tags by a specific prefix. If we had variant names in tags, tag updates triggered by those solutions would float over multiple prefixes(like floating over debian and ubuntu). Making the variant name a part of the image name fixes it, resulting in a solution to select the latest version out of the all image tags for the specific variant(debian or ubuntu or whatever we might support).

I'd love it if we could have these two images in the end:

- `helmfile-ubuntu:$VER`
- `helmfile-debian:$VER`

Not because it's more common to have the base image variant in the derived image's tag, but because I prefer it agnostic to the variant of the base image, I like naming it `Dockerfile.ubuntu` along with the way how the GH action workflow is implemented in this PR now.

I'd "eventually" want to rename `Dockerfile.debian-stable-slim` to `Dockerfile.debian` for the same reason, and bring back additional variants like `debian-stable-slim` or `debian-buster` or whatever if and only if it makes sense. To keep the backward-compatibility though, I'd like to refrain from making such a change in this PR.

All that said, the state of this PR LGTM!

If you agree, I'd be happy to merge this PR as-is, and defer other matters to another issues/discussions.

WDYT?

**Comment by yxxhero** [comment]
@mumoshu I agree with you. Thanks very much.

**Review by mumoshu — APPROVED** [review]
LGTM. Thanks a lot for your efforts @pathob ☺️

**Comment by pathob** [comment]
@mumoshu I agree with you too, that would be a nice solution at the end and a task for another PR / discussion.

**Comment by yxxhero** [comment]
@pathob @mumoshu So let we merge this PR. Thanks very much. Thanks for your good work.

**Pull request merged**
