### PR TITLE
Improve some multi-value flags to accept comma-separated values

### PR DESCRIPTION
**Pull request by yxxhero**
Signed-off-by: yxxhero <aiopsclub@163.com>

an improvement for cobra

`StringSliceVar` defines a string flag with specified name, default value, and usage string. The argument p points to a []string variable in which to store the value of the flag. Compared to StringArray flags, StringSlice flags take comma-separated value as arguments and split them accordingly. 

`StringArrayVar` defines a string flag with specified name, default value, and usage string. The argument p points to a []string variable in which to store the values of the multiple flags. The value of each argument will not try to be separated by comma. Use a StringSlice for that.

@mumoshu

### CODE REVIEW

**Review by mumoshu — APPROVED** [review]
LGTM. Thanks a lot for the improvement!

**Comment by yxxhero** [comment]
@mumoshu only StringSliceVar support comma-separated values. Now is StringArrayVar. So the title is mistake. If we need support comma-separated values,  I will create a new PR for it.

**Comment by mumoshu** [comment]
@yxxhero Ah sorry! So it's the opposite than what I thought. So, this is indeed a fix. Sorry about that. I'm fixing the title

**Comment by mumoshu** [comment]
So this is indeed a regression introduced by our migration to cobra. Gotcha!

**Comment by yxxhero** [comment]
@mumoshu Thanks very much.

**Pull request merged**
