### PR TITLE
feat: add --skip-trailing-cr to helmfile diff

### PR DESCRIPTION
**Pull request by rezonant**

### CODE REVIEW

**Comment by mumoshu** [comment]
@rezonant Please start with a GitHub discussion or a concise description of your pull request so we can review your work. Thanks!

**Comment by rezonant** [comment]
@mumoshu This is drafted, not quite ready for review, I'm having trouble with some of the e2e tests and was hoping to check if the issue was local or an issue with the changeset.

When this is ready for review there will be rationale in the PR description, but for now, please see https://github.com/roboll/helmfile/issues?q=is%3Aissue+is%3Aopen+strip-trailing-cr where you requested someone to send in a PR for this issue, which prevents us from using helm diff across CRLF/CR systems:

https://github.com/roboll/helmfile/issues/1918#issuecomment-1143037230

**Comment by mumoshu** [comment]
@rezonant That would be enough context! Thanks a lot for your explanation and contribution ☺️ Looking forward to seeing this become ready for review!

**Comment by mumoshu** [comment]
I've enabled CI for this pull request so that you can see the results.

**Comment by yxxhero** [comment]
@rezonant please fix DCO issue. Thanks very muhc.

**Comment by rezonant** [comment]
@yxxhero Hi! This is a draft PR that is not yet ready for review. The commits in it will be rebased and relabeled before the PR is submitted for review. Thanks for your patience.

**Comment by yxxhero** [comment]
@rezonant ok. when PR is ready please ping me.

**Comment by yxxhero** [comment]
@rezonant ping. any updates?

**Comment by yxxhero** [comment]
@rezonant any updates?

**Comment by yxxhero** [comment]
@mumoshu WDYT about this PR? I fixed the lint issues.

**Review by yxxhero — APPROVED** [review]

**Review by xiaomudk — APPROVED** [review]

**Comment by xiaomudk** [comment]
@yxxhero @rezonant  Great job, i have nothing to add

**Pull request merged**
