### PR TITLE
fix output-dir issue

### PR DESCRIPTION
**Pull request by yxxhero**
Signed-off-by: yxxhero <aiopsclub@163.com>

Fixed: https://github.com/helmfile/helmfile/issues/30

### CODE REVIEW

**Review by itscaro — APPROVED** [review]

**Comment by itscaro** [comment]
@yxxhero Could you check where the final path is constructed? with filepath.Join(), we should not have to trim slash in input?
Thank you for your contribution.

**Comment by yxxhero** [comment]
outputDirTemplate = filepath.Join("{{ .OutputDir }}", "{{ .State.BaseName }}-{{ .State.AbsPathSHA1 }}-{{ .Release.Name}}")
The code use go template. @itscaro

**Comment by itscaro** [comment]
I see, if we do slash-trimming in  input, could you please trim "\" for windows too?

Or, maybe it's better to replace double `os.PathSeparator` here?
https://github.com/helmfile/helmfile/blob/f1a250cab3e661b0196b4c98c0ee47e51089ae7c/pkg/state/state.go#L3116

**Comment by yxxhero** [comment]
ok. got it. I forget the window platform. I will see it latter. @itscaro

**Review by mumoshu — APPROVED** [review]
LGTM. Thanks a lot for fixing it @yxxhero ☺️

**Pull request merged**
