### PR TITLE
bump go 1.18 & remove .circleci

### PR DESCRIPTION
**Pull request by itscaro**

### CODE REVIEW

**Comment by mumoshu** [comment]
@itscaro Thanks for the PR! Please feel free to mark it as ready for review. Draft PRs aren't actionable so it would be great if you can avoid it, or explicitly ask any of the maintainers for comments!

**Review by mumoshu — APPROVED** [review]
LGTM. Thanks for your contribution!
It would be great if you could address the DCO failure by reviewing steps explained in https://github.com/helmfile/helmfile/pull/2/checks?check_run_id=5804778252 when you have some time.

**Review by jduepmeier — CHANGES_REQUESTED** [review]
The makefile in .circleci is called here: https://github.com/helmfile/helmfile/blob/main/.github/workflows/ci.yaml#L91

**Review by mumoshu — APPROVED** [review]
LGTM. Thanks for your contribution!

**Pull request merged**
