### PR TITLE
Add chinese readme

### PR DESCRIPTION
**Pull request by xiaomudk**
Signed-off-by: xiaomudk <xiaomudk@gmail.com>

### CODE REVIEW

**Comment by yxxhero** [comment]
@xiaomudk `README.md` had some updates. please check your Readme in the PR. and would you mind add a super link that link to the chinese readme in README.md?

**Comment by xiaomudk** [comment]
@yxxhero Thanks. This is a first version, I will continue to improve it.

**Review by yxxhero — APPROVED** [review]

**Review by mumoshu — APPROVED** [review]
LGTM!
It would be even nicer if we could add a whole new readthedocs project for the zh_CH version of the documentations ite, add a Language switcher to our docs site 😃 
https://helmfile.readthedocs.io/en/latest/
https://docs.readthedocs.io/en/stable/localization.html

**Comment by yxxhero** [comment]
@mumoshu good idea.

**Pull request merged**
