### PR TITLE
add subshell to USERS.md

### PR DESCRIPTION
**Pull request by philmtd**

### CODE REVIEW

**Comment by yxxhero** [comment]
@philmtd Please fix DCO issue.

**Comment by philmtd** [comment]
Done. :)

**Comment by yxxhero** [comment]
@philmtd Thanks very much. Are you interested in contributing together?

**Review by yxxhero — APPROVED** [review]

**Comment by yxxhero** [comment]
@philmtd oh. welcome. Thanks very much.

**Pull request merged**
