### PR TITLE
Redact sensitive informations like password in chart url

### PR DESCRIPTION
**Pull request by dol**
The chart name can also be an URL that contains basic authentication information. This information are printed out by helmfile. This PR tries to redact this information.

```
$ cat <<EOT >> helmfile.yaml
releases:
    - name: test
      chart: https://foo:bar@charts.helm.sh/incubator/packages/druid-0.2.13.tgz
EOT

$ helmfile template
> Templating release=test, chart=https://foo:bar@charts.helm.sh/incubator/packages/druid-0.2.13.tgz
```

With this patch the output looks like:
```
> Templating release=test, chart=https://foo:xxxxx@charts.helm.sh/incubator/packages/druid-0.2.13.tgz
```` 

Moved from roboll/helmfile => roboll/helmfile#2132

### CODE REVIEW

**Comment by itscaro** [comment]
@dol Thank you for your contribution, this looks great! Could you please add a simple unit test to the function?

**Comment by dol** [comment]
@itscaro Will try.

**Comment by dol** [comment]
I extended the test cases and removed the redacting in some of the methods based on this list.

|Method|helm command supports URL    |
|------|-----------------------------|
|BuildDeps|no                           |
|UpdateDeps|no                           |
|SyncRelease|yes                          |
|TemplateRelease|yes                          |
|DiffRelease|yes                          |
|Lint  |no                           |
|Fetch |yes                          |
|ChartPull (OCI)|no                           |
|ChartExport (OCI)|no                           |

**Review by itscaro — APPROVED** [review]
LGTM 👍

**Review by mumoshu — APPROVED** [review]
LGTM. Thanks a lot for your work @dol ☺️

**Pull request merged**
