### PR TITLE
feat: use helm status to find helm release

### PR DESCRIPTION
**Pull request by yxxhero**

### CODE REVIEW

**Review by mumoshu — CHANGES_REQUESTED** [review]
Awesome!!! Really excited to see we still encounter an opportunity like this to make Helmfile more efficient...

This LGTM mostly. One thing though- can we add a test case within "TestApply", with

- `name: "with helm-status-check-release-existence"`
- some helm-status call expectations in the test instead of on helm-list (similar to https://github.com/helmfile/helmfile/blob/fb7046292bfec07b19726b48d69b462b7ad3b927/pkg/app/app_test.go#L2728)

which might be sufficient to test that it works?

**Comment by yxxhero** [comment]
@mumoshu I will try to add some tests for this PR.

**Comment by yxxhero** [comment]
@mumoshu ping

**Review by mumoshu — APPROVED** [review]
LGTM. Awesome work!!

**Pull request merged**
