### PR TITLE
Add logo as .png and .ai (Adobe Illustrator) files

### PR DESCRIPTION
**Pull request by pathob**
Referring to https://github.com/helmfile/helmfile/discussions/38

### CODE REVIEW

**Comment by yxxhero** [comment]
@mumoshu I contacted the previous logo author, but there was no response. I think this logo is also very good, what do you think?

**Comment by yxxhero** [comment]
@pathob Did you design this logo yourself? Will there be any intellectual property problems?

**Comment by pathob** [comment]
> @pathob Did you design this logo yourself? Will there be any intellectual property problems?

Yes, I made the file icon myself. The 'HELM' text is from the official Helm logo, I'm not 100% sure whether it's okay to use it. The 'file' text is based on this font: https://www.dafont.com/best-valentina.font?fpp=200 I consider helmfile non-profit, so it should be fine to use it. In doubt I would donate the 4.80 USD to buy it and put a note about the purchase somewhere.

Let me know if anything needs to be changed from your perspective.

**Comment by yxxhero** [comment]
@pathob I think all is very good. thanks very much. wait for @mumoshu . Thanks very much again.

**Comment by pathob** [comment]
And I could also add the Adobe Illustrator (.ai) file if you like

**Comment by yxxhero** [comment]
> And I could also add the Adobe Illustrator (.ai) file if you like

yes. How size?

**Comment by pathob** [comment]
> yes. How size?

229 KB

**Comment by yxxhero** [comment]
> > yes. How size?
> 
> 229 KB

wait for @mumoshu

**Comment by mumoshu** [comment]
@pathob Hey! Thanks a lot for your contribution. I def love the look&feel of the logo. Awesome job ❤️ 

Unfortunately though, the use of "HELM" seems to violate their trademark. I've emailed a representative of the matter in CNCF via email and the response was like this:

```
Unfortunately you can not use derived versions, we try to give you a more detailed policy here:
https://www.linuxfoundation.org/trademark-usage/
```

If you're curious, the sentences in my email was like:

```
Can we use this logo (https://github.com/helmfile/helmfile/pull/263/files) without any trademark or license violation?

We're afraid because we think it's considered "derived" from the Helm logo (https://github.com/cncf/artwork/blob/master/projects/helm/icon/white/helm-icon-white.svg), because the "HELM" part of our logo is using the same font and the style with the original Helm logo.
```

Probably changing the font used in the word "HELM" will make it ok (I believe the word "HELM" itself is very common and obviously not retained by the Helm project so changing the style of the word in the logo is enough to make it totally a new logo that is not considered "derived".

**Comment by yxxhero** [comment]
@pathob ping

**Comment by yxxhero** [comment]
> Hi @yxxhero Sorry, I wasn't home for a couple of days and didn't have access to Illustrator.
> 
> Hi @mumoshu , thank you for contacting the CNCF regarding this topic.
> 
> I've now changed the font to https://www.dafont.com/de/made-tommy.font?text=HELM
> 
> It comes with the same limitation as the other font ("for personal use only" (== for non-commercial use only?)) and looks quite similar to the original Helm font but is still different, thus not derived anymore I would assume too. For a direct comparison have a look at the following image (the blue font is the Helm font, the black font is the MADE Tommy font).
> 
> helm_font_comparison
> 
> Please still let me know whether you want to have the Illustrator file checked in too.

@mumoshu ping

**Comment by mumoshu** [comment]
@pathob Thank you so much for your effort! The new font looks good. And yeah, I'd greatly appreciate it if you could share the original illustrator file so that we can co-maintain it!

**Comment by pathob** [comment]
I've also checked in the Illustrator file now, hope this is ready to be merged now :)

**Comment by pathob** [comment]
@mumoshu @yxxhero I've also checked in the Illustrator file now, hope this is ready to be merged now :)

**Review by yxxhero — APPROVED** [review]
LGTM

**Comment by yxxhero** [comment]
@pathob @mumoshu @itscaro looking forward the first logo for helmfile.

**Comment by yxxhero** [comment]
@mumoshu WDYT? Can we merge this PR? Thanks very much.

**Review by mumoshu — APPROVED** [review]
Perfect! Thank you so much for your contribution!
I'm super excited that we can finally have a cool logo for the first time in 5 years maintaining this project 😂

**Pull request merged**
