### PR TITLE
move all subcommand to sigle file

### PR DESCRIPTION
**Pull request by yxxhero**
Signed-off-by: yxxhero <aiopsclub@163.com>

move all subcommand to sigle file

### CODE REVIEW

**Review by renehernandez — APPROVED** [review]
Nice! Great refactoring!

**Comment by renehernandez** [comment]
> @renehernandez Can you merge this PR? Thanks very much.

It doesn't let me 😔 It still requires another review. Not sure why

**Comment by yxxhero** [comment]
@mumoshu ping

**Comment by mumoshu** [comment]
@renehernandez Perhaps you are not added as a maintainer to this repo yet? I thought I've already invited you so please check your inbox for the invitation and accept it 🙏

**Comment by mumoshu** [comment]
@renehernandez I do see you have the write access to this repo so that's ok. Perhaps the issue is that you might have approved it as `helmfile/maintainers` but it doesn't count to the number of required approvals 🤔 Perhaps you can approve as yourself instead.

CleanShot 2022-06-11 at 17 06 56@2x

**Review by mumoshu — APPROVED** [review]

**Comment by mumoshu** [comment]
It happened to me as well 😂 And it worked this time. Not sure what made the difference, but keep trying!

CleanShot 2022-06-11 at 17 09 28@2x

**Pull request merged**
