### PR TITLE
chore: update Jenkins's main helmfile repository in USERS

### PR DESCRIPTION
**Pull request by lemeurherve**
Signed-off-by: lemeurherve hlemeur@cloudbees.com

Update Jenkins Infrastructure helmfile repository location.

### CODE REVIEW

**Comment by lemeurherve** [comment]
If possible, it would be really great if the Jenkins project could also be quoted in the README like Gitlab and Reddit (cf https://github.com/helmfile/helmfile/pull/317/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R117)

**Comment by yxxhero** [comment]
@lemeurherve Sure. I will do.

**Comment by yxxhero** [comment]
@lemeurherve please update helmfile repo link in https://github.com/jenkins-infra/kubernetes-management. Thanks very much.

**Review by yxxhero — APPROVED** [review]
LGTM

**Pull request merged**
