### PR TITLE
update Readmd.md

### PR DESCRIPTION
**Pull request by yxxhero**
update Readmd.md

Signed-off-by: yxxhero <aiopsclub@163.com>

### CODE REVIEW

**Review by mumoshu — COMMENTED** [review]
Hey. Where do all the config and instalation docs go?

**Comment by yxxhero** [comment]
@mumoshu [helmfile.readthedocs.io](https://helmfile.readthedocs.io/)

**Comment by mumoshu** [comment]
@yxxhero Thanks! But I don't get. The section like https://helmfile.readthedocs.io/en/latest/#configuration is generated from the README. If you removed it from the README, the section in the doc site would also gets removed.

**Comment by yxxhero** [comment]
The section like https://helmfile.readthedocs.io/en/latest/#configuration is generated from the docs/index.md.

**Comment by yxxhero** [comment]
@mumoshu You can see mkdoc.yaml

**Comment by mumoshu** [comment]
@yxxhero Ah, sorry! I didn't realize that you changed the `dosc/index.md` from a symlink to a copy of the current README.md in https://github.com/helmfile/helmfile/pull/224(is that correct?

**Comment by yxxhero** [comment]
@mumoshu yes. haha

**Review by mumoshu — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
