### PR TITLE
feat: release status precheck before apply and sync

### PR DESCRIPTION
**Pull request by yxxhero**
feat: release status precheck before apply and sync

### CODE REVIEW

**Comment by yxxhero** [comment]
/cc @mumoshu @xiaomudk 
add release status precheck for apply sync delete and destroy. only not pending status can continue.

**Comment by mumoshu** [comment]
@yxxhero I'm a bit confused but why do you need this when we already have `--wait` in helmfile.yaml and `wait: true/false` as a command-line flag?

**Comment by yxxhero** [comment]
@yxxhero let me explain:
`--wait`:
if set, will wait until all Pods, PVCs, Services, and minimum number of Pods of a Deployment, StatefulSet, or ReplicaSet are ready before marking the release as successful. It will wait for as long as --timeout

`--wait-release-available`:
this flag will wait for the release to come to ready status(not pending), use case: in the dev branch. users can trigger helmfile deployment at the same time. if the helm release is in the pending status. the helmfile will be failed directly. it's not friendly.

they are different-level flags.

**Comment by mumoshu** [comment]
> this flag will wait for the release to come to ready status(not pending), use case: in the dev branch. users can trigger helmfile deployment at the same time. if the helm release is in the pending status. the helmfile will be failed directly. it's not friendly.

Thanks for clarifying @yxxhero! I got it now.

However, I'm afraid this doesn't make much sense as there can still be a third user who can run `helmfile` with the new flag. In that case, both you and the third person race against the same helm release AFTER the release became ready.

If that's the user case, I would rather suggest either of the below:

- Let Helmfile return a specific exit code when it detected the helm command failing due to this issue(=helm release is pending) so that the external tool/process can retry the helmfile run.
- Let Helmfile retry a helm command that failed due to this issue (when the flag is provided). If there are multiple interfering helmfile invocations across machines, all of those might eventually finish as each retry forever for the release pending error.

**Comment by yxxhero** [comment]
@mumoshu makes sense. let me think about it more.

**Pull request closed without merging**
