### PR TITLE
Add support for printing the DAG

### PR DESCRIPTION
**Pull request by justindriggers**
Usage: `helmfile build --dag`

Resolves:
- https://github.com/roboll/helmfile/issues/1013
- https://github.com/roboll/helmfile/issues/1916

### CODE REVIEW

**Comment by yxxhero** [comment]
@justindriggers please fix DCO.

**Comment by justindriggers** [comment]
Apologies, fixed

**Comment by yxxhero** [comment]
@justindriggers please fix the lint error.

**Comment by justindriggers** [comment]
@yxxhero Done. I'm not particularly experienced with Golang so please let me know if there's anything I can improve

**Comment by yxxhero** [comment]
@mumoshu ping

**Comment by yxxhero** [comment]
see: https://github.com/helmfile/helmfile/pull/1477

**Pull request closed without merging**
