### PR TITLE
test: add template anchors merge e2e test

### PR DESCRIPTION
**Pull request by yxxhero**
Signed-off-by: yxxhero <aiopsclub@163.com>

test: add template anchors merge e2e test

related: https://github.com/helmfile/helmfile/issues/493

### CODE REVIEW

**Comment by yxxhero** [comment]
@mumoshu @itscaro

**Review by itscaro — APPROVED** [review]

**Comment by itscaro** [comment]
A test failed?

**Comment by yxxhero** [comment]
@itscaro fixed

**Comment by yxxhero** [comment]
@itscaro done

**Review by itscaro — APPROVED** [review]

**Pull request merged**
