### PR TITLE
feat: support most remote urls

### LINKED ISSUE #831: Go getter urls only work for 'git' prefix
### Operating system

Mac OS 12.4

### Helmfile Version

v0.153.1

### Helm Version

v3.11.3

### Bug description

According to the docs we should be able to use go-getter urls. It's not clear that only `git` urls are supported because perhaps underlying go-getter is not used? 
https://helmfile.readthedocs.io/en/latest/#loading-remote-environment-values-files

### Example helmfile.yaml

```yaml
releases:
  - chart: charts/hello
    name: hello
    version: 0.1.0
    values:
      - values/hello.values.yaml.gotmpl
  - chart: charts/message
    name: message
    version: 0.1.0
    values:
      - values/message.values.yaml.gotmpl
---
environments:
  default:
    values:
      - data/exclaim.values.yaml
      - data/first.values.yaml
      - data/last.values.yaml
      - git::https://github.com/woodcockjosh/s3-values@/examples/data/message.values.yaml?ref=main
      - git::https://github.com/woodcockjosh/s3-values@/examples/data/values.yaml?ref=main
      # Should work but doesn't
#      - s3::https://helm-s3-values-example.s3.us-east-2.amazonaws.com/values.yaml
#      - s3::helm-s3-values-example.s3.amazonaws.com/values.yaml
      # Doesn't work
#      - https://john:doe@helm-s3-values-example.s3.us-east-2.amazonaws.com/values.yaml
#      - https://helm-s3-values-example.s3.us-east-2.amazonaws.com/values.yaml
#      - http:://helm-s3-values-example.s3.us-east-2.amazonaws.com/values.yaml
#      - http:://helm-s3-values-example.s3.us-east-2.amazonaws.com/values.yaml
#      - s3:://helm-s3-values-example/values.yaml
      # Could work if s3-values plugin was incorporated into helmfile
#      - s3://helm-s3-values-example/values.yaml
```

### Error message you've seen (if any)

```text
in ./helmfile.yaml: failed to read helmfile.yaml: environment values file matching "s3::https://helm-s3-values-example.s3.us-east-2.amazonaws.com/values.yaml" does not exist in "."
```

### Steps to reproduce

https://github.com/woodcockjosh/s3-values/blob/main/examples/helmfile.yaml

### Working Helmfile Version

N/A

### Relevant discussion

https://github.com/helmfile/helmfile/discussions/792

### PR DESCRIPTION
**Pull request by woodcockjosh**
This adds support for s3:// http:// https:// and most other go-getter style urls by

- Adding http downloader
- Adding s3 downloader that authenticates with aws sdk shared credentials
- Changing the parser to accept remote formats that do not include '::'
- Removing validation that required go-getter urls to contain '@' which is not required by go-getter spec

Resolves #831

### CODE REVIEW

**Comment by yxxhero** [comment]
Please fix DCO issue.

**Comment by yxxhero** [comment]
DCO

**Comment by yxxhero** [comment]
Please follow the link https://github.com/helmfile/helmfile/pull/834/checks?check_run_id=13084972900 to fix DCO issue.

**Comment by yxxhero** [comment]
@woodcockjosh

**Comment by yxxhero** [comment]
And indent should be four spaces. Thanks very much. @woodcockjosh

**Comment by woodcockjosh** [comment]
I put this "Signed-off-by: Josh Woodcock <josh.woodcock@cryptexlabs.com>" in the commit message. Idk what is the issue.

**Comment by yxxhero** [comment]
@woodcockjosh why closed? thanks so much.

**Comment by woodcockjosh** [comment]
Sorry I don't have time to do things the right way so it doesn't belong in the code base. Feel free to use what I have as a starting point.

**Comment by yxxhero** [comment]
@xiaomudk 👍

**Comment by yxxhero** [comment]
@xiaomudk DCO.

**Pull request closed without merging**
