### PR TITLE
feat: optimize version output

### PR DESCRIPTION
**Pull request by yxxhero**
Signed-off-by: yxxhero <aiopsclub@163.com>

```bash

▓▓▓ ./helmfile

  Version            0.145.4
  Git Commit         N/A
  Build Date         N/A
  Commit Date        N/A
  Dirty Build        no
  Go version         1.19
  Compiler           gc
  Platform           linux/amd64

  │ A new release is available: 0.145.4 → v0.146.0
  │ https://github.com/helmfile/helmfile/releases/tag/v0.146.0


[root@devops helmfile]# ./helmfile version -o json
{
  "buildDate": "N/A",
  "commitDate": "N/A",
  "compiler": "gc",
  "gitCommit": "N/A",
  "goVersion": "go1.19",
  "platform": "linux/amd64",
  "version": "0.145.4"
}

  │ A new release is available: 0.145.4 → v0.146.0
  │ https://github.com/helmfile/helmfile/releases/tag/v0.146.0
```

### CODE REVIEW

**Review by mumoshu — COMMENTED** [review]
LGTM overall!
Can we also add a flag to disable the new version check feature for cases where helmfile is used in an isolated/restrictive environment with no internet access?

**Comment by yxxhero** [comment]
@mumoshu set HELMFILE_UPGRADE_NOTICE_DISABLED to any not empty value to disable upgrade notice behavior.

**Review by mumoshu — DISMISSED** [review]
LGTM. Thank you as always for your effort!

**Comment by yxxhero** [comment]
@mumoshu fix the ci error. done.

**Review by mumoshu — APPROVED** [review]
Perfect! Thanks a bunch!

**Pull request merged**
