### PR TITLE
[feature] add --skip-refresh to globals

### PR DESCRIPTION
**Pull request by sstarcher**
--skip-deps ties together build deps and helm repo update this allows for us to skip the repo up,but still build the deps

### CODE REVIEW

**Comment by yxxhero** [comment]
image

**Comment by sstarcher** [comment]
@yxxhero thanks everything is green

**Comment by yxxhero** [comment]
@sstarcher did you test it locally?  or maybe add some test for this feature?

**Comment by sstarcher** [comment]
I did test it locally with
* helmfile template > builds/deps both done
* helmfile template --skip-deps > no builds / no deps
* helpfile template --skip-refresh > no deps / builds happen
* helmfile template --skip-deps --skip-refresh > no deps / no builds

**Review by yxxhero — APPROVED** [review]

**Comment by sstarcher** [comment]
Thank you for your help

**Pull request merged**
