### PR TITLE
feat: retrieve repository's username/password from environment

### PR DESCRIPTION
**Pull request by kevinleturc**
Make possible to retrieve username/password from the environment for Helm repositories, like it is done for OCI registries.

Related to https://github.com/roboll/helmfile/pull/1629

### CODE REVIEW

**Comment by yxxhero** [comment]
@kevinleturc please fix lint error.

**Comment by kevinleturc** [comment]
Sorry for the lint, I've just fixed it with `make fmt`, should be enough right?

**Comment by yxxhero** [comment]
@kevinleturc yes. It's enough. Thanks for your work on this feature.

**Comment by kevinleturc** [comment]
If I understand correctly `TestHelmfileTemplateWithBuildCommand/oci_chart_pull` is failing, I'm having a look.

**Comment by kevinleturc** [comment]
@yxxhero we should be good now, I fixed `TestHelmfileTemplateWithBuildCommand/oci_chart_pull`.

Thanks for your time!

**Comment by yxxhero** [comment]
@kevinleturc good work. keep going on.

**Review by yxxhero — APPROVED** [review]
LGTM

**Comment by yxxhero** [comment]
@mumoshu

**Pull request merged**
