### PR TITLE
Refactor cobra flag default values for readability

### PR DESCRIPTION
**Pull request by yxxhero**
Signed-off-by: yxxhero <aiopsclub@163.com>

fix cobra flag default value

### CODE REVIEW

**Comment by yxxhero** [comment]
@mumoshu @itscaro

**Review by mumoshu — COMMENTED** [review]
@yxxhero Is this actually a fix? I mean, are there any functional changes in this PR? 🤔

**Comment by yxxhero** [comment]
@mumoshu Generally speaking, there is no change, but the default value is changed, which is consistent with the previous mode and easier to read.

**Review by mumoshu — DISMISSED** [review]
LGTM. Thanks for the improvement!

**Comment by mumoshu** [comment]
@yxxhero I fixed the merge conflicts in [eabf360](https://github.com/helmfile/helmfile/pull/274/commits/eabf360fe85bc3f34024747b11219e4347b0fc0e). Does that look good to you?

**Comment by yxxhero** [comment]
@mumoshu LGTM

**Review by mumoshu — APPROVED** [review]

**Pull request merged**
