### PR TITLE
docs: add docs for helmfile list

### PR DESCRIPTION
**Pull request by stek29**

### CODE REVIEW

**Comment by yxxhero** [comment]
https://github.com/helmfile/helmfile/blob/main/docs/index.md#cli-reference and this.

**Comment by stek29** [comment]
@yxxhero done

**Review by yxxhero — APPROVED** [review]

**Comment by stek29** [comment]
@yxxhero could you please make a new release with these changes now?

**Comment by yxxhero** [comment]
@stek29 wait for #342 #348

**Pull request merged**
