### PR TITLE
bump github.com/helmfile/vals

### PR DESCRIPTION
**Pull request by jkroepke**
Implementing https://github.com/helmfile/vals/pull/161

### CODE REVIEW

**Comment by yxxhero** [comment]
please use v0.27.1.

**Review by yxxhero — APPROVED** [review]
LGTM

**Comment by jkroepke** [comment]
Thanks @yxxhero ,

when I can expect the next release? 👍

**Comment by yxxhero** [comment]
@jkroepke in three weeks.

**Pull request merged**
