### PR TITLE
feat: make environment context available

### PR DESCRIPTION
**Pull request by SeWieland**
This feature adds the `{{.Environment.KubeContext}}` variable.

Discussion #829

### CODE REVIEW

**Comment by mumoshu** [comment]
Hey @SeWieland! How is this supposed to be inherited to `releases[].kubecontext`? I'd expect it to be inherited if you call this kubecontext... Otherwise this is almost an alias to `.Environments.Values.kubecontext` which you can achieve today with:

```
environments:
  prod:
    values:
    - kubecontext: foobarbaz
```

**Comment by SeWieland** [comment]
Hi @mumoshu!

1. As can be seen in #829, I have a situation where I need to access the kubecontext (set on the environment level) in the helmfile hooks
1. It is not supposed to propagate to releases[].kubecontext at all - {{.Release.KubeContext}} can already be used, but is empty if set on the environment level, so the behaviour here is identical

**Comment by mumoshu** [comment]
Thanks @SeWieland! Just wondering, but why

>  but I'll have to set it twice in order to function

Why do you need to set it twice?

**Comment by SeWieland** [comment]
When using only

```yaml
environments:
  prod:
    values:
    - kubeContext: foobarbaz
```

`helmfile -e prod apply` would deploy to the current context instead of `foobarbaz` by default @mumoshu

**Comment by mumoshu** [comment]
@SeWieland Ah thanks a lot for the explanation! I was pretty confused how it works today.

So we already have `environements[].kubeContext` that becomes the default `--kubecontext` value when there are no `releases[].kubeContext` defined, without affecting `.Release.KubeContext`.

Your change exposes the existing `environments[].kubeContext` to the helmfile template so that you can use it to dynamically render the release hook args from it. Am I following you correctly?

**Comment by SeWieland** [comment]
@mumoshu yes, this is exactly what I need.

I also compiled and tested the changes in my setup and everything works as expected.
I don't know why the go tests failed however. I'm not a go dev, so it's pretty hard for me to understand my small changes break anything.

**Comment by mumoshu** [comment]
@SeWieland Thanks for your confirmation!

The test failure might be due to unintended changes in the debug log format due to the new environment struct field.

```
        - first-pass produced: &{default map[] map[]}
        - first-pass rendering result of "helmfile.yaml.part.0": {default map[] map[]}
        + first-pass produced: &{default  map[] map[]}
        + first-pass rendering result of "helmfile.yaml.part.0": {default  map[] map[]}
          vals:
          map[]
          defaultVals:[]
        ...
          22:   - default/external-secrets
          23: 
          
        - merged environment: &{default map[] map[]}
        + merged environment: &{default  map[] map[]}
```

I'll try to fix the test by updating the test snapshots to reflect the new debug logs.

**Comment by SeWieland** [comment]
@mumoshu I tried to fix the test issues using a regex replace of `(\{[a-z]*) (map\[\] map\[\]\})` => `$1  $2` in order to add the "missing" space to all log outputs.
I also rebased the branch on the current main.

The end2end tests still did not run on my setup, but I'm not sure if the issues were related to the changes after all.

Please have a look, thank you!

**Comment by yxxhero** [comment]
@SeWieland omg. 139 files changed.

**Comment by yxxhero** [comment]
@SeWieland please update the doc about this PR.

**Comment by SeWieland** [comment]
@yxxhero what exactly do you mean with the docs about this PR?

Should I just update the initial comment of the PR?

The PR actually just introduces very small code change (first commit).
The second commit that introduced the massive amount of changes just fixes the issues explained in https://github.com/helmfile/helmfile/pull/832#issuecomment-1528708152 (mainly updates of log snapshots)

I really want this feature to be merged, so I proposed a very simple fix using a regex replace approach.
I also tried a different approach using a custom Stringer method for the environment struct, but I could not work around the issues without massive snapshot updates here as well.

I'm completely open to any other suggestions!

**Comment by yxxhero** [comment]
https://helmfile.readthedocs.io/en/latest/builtin-objects/

**Comment by yxxhero** [comment]
@SeWieland awesome. maybe we should add some tests for this new feature.

**Comment by SeWieland** [comment]
@yxxhero Sure! I added a small test in order to check if the `Environment.KubeContext` is mapped out correctly and available.

**Comment by yxxhero** [comment]
@SeWieland awesome. thanks so much.

**Comment by yxxhero** [comment]
@SeWieland please fix lint errors.

**Comment by SeWieland** [comment]
@yxxhero Done!

Looks to me that the linting + test checks are green now, however one integration test failed during the "Install test dependencies" step.
Is that a transient error? Should I try and trigger a restart of the checks by force pushing?

**Comment by yxxhero** [comment]
@SeWieland rerun. done.

**Review by mumoshu — APPROVED** [review]
LGTM! Thanks a lot for your patience and contribution @SeWieland!

**Review by mumoshu — APPROVED** [review]
LGTM! Thanks a lot for your patience and contribution @SeWieland!

**Pull request merged**
