### PR TITLE
build image on tag

### PR DESCRIPTION
**Pull request by itscaro**
I did not test.

### CODE REVIEW

**Comment by mumoshu** [comment]
@itscaro Probably we'd better have another repository to test things like this?

**Comment by itscaro** [comment]
I don't have preference @mumoshu

**Comment by mumoshu** [comment]
@itscaro Thanks! So I went ahead and merged it anyway. My first finding is that it fails when ran on our `main` branch: https://github.com/helmfile/helmfile/runs/6541933388?check_suite_focus=true

**Comment by itscaro** [comment]
@mumoshu sorry for the failure, i will check it today or tomorrow.

**Comment by itscaro** [comment]
@mumoshu I committed directly to main the fix

**Pull request merged**
