### PR TITLE
Sops and gpg command

### PR DESCRIPTION
**Pull request by metajiji**
Added gpg command to be able to use sops

This package is required for importing gpg keys

```bash
gpg --import < gpg.file
```

### CODE REVIEW

**Comment by yxxhero** [comment]
@metajiji Thanks very much. In my opinion. you could try to build your own image based the helmfile image.

**Comment by yxxhero** [comment]
@mumoshu WDYT?

**Comment by metajiji** [comment]
> @metajiji Thanks very much. In my opinion. you could try to build your own image based the helmfile image.

Yes i can, but `sops` binary more usable with `gpg` command :)

**Comment by yxxhero** [comment]
@metajiji DCO issue in ci.

**Review by itscaro — APPROVED** [review]

**Comment by yxxhero** [comment]
@metajiji there are three dockerfiles. all of them should be updated.

**Comment by metajiji** [comment]
> @metajiji there are three dockerfiles. all of them should be updated.

Done!

**Comment by yxxhero** [comment]
@metajiji please fix DCO issue.

**Comment by yxxhero** [comment]
@metajiji https://github.com/helmfile/helmfile/pull/597/checks?check_run_id=10273746349

**Review by yxxhero — APPROVED** [review]

**Pull request merged**
