### PR TITLE
feat: bump chartify to v0.10.0 to support OCI registry for adhoc dependencies

### PR DESCRIPTION
**Pull request by toVersus**
Signed-off-by: Tsubasa Nagasawa <toversus2357@gmail.com>

This adds OCI registry support for adhoc dependencies.
The users can now add their OCI hosted charts as dependencies to helm releases:

* Bump chartify version to [v0.10.0](https://github.com/variantdev/chartify/releases/tag/v0.10.0)
* Add an example helmfile to advanced usage section

xref: https://github.com/variantdev/chartify/pull/33

### CODE REVIEW

**Comment by yxxhero** [comment]
@toVersus Thanks very much, Can you add a test for this.

**Comment by mumoshu** [comment]
@yxxhero This is purely a chartify-side change so I think it isn't unit-testable from within helmfile. Do you think adding an integration test case that depends on an external ocr repo make sense in this case? (Probably it makes our integration test much more unreliable due to any external ocr repo and access to it isn't 100% reliable

**Comment by yxxhero** [comment]
@toVersus Yes. I agree.

**Review by yxxhero — APPROVED** [review]

**Comment by yxxhero** [comment]
@mumoshu should we create a release for this feat?

**Comment by toVersus** [comment]
> Probably it makes our integration test much more unreliable due to any external ocr repo and access to it isn't 100% reliable

I'm not sure it is a right choice but we can manage an OCI helm chart on GitHub container registry and use it for our integration tests.

xref: https://dev.to/niklasmtj/use-github-container-registry-ghcr-to-host-your-helm-charts-nef

**Comment by mumoshu** [comment]
@yxxhero @toVersus Hey! Would you mind taking a look at #239?

It was a long-standing TODO to add more features to the integration test framework so that we could easily write tests for features like this one so here it is.

I opted to use a local docker registry instead of a remote one(like GHCR) hoping it might reduce test flakes.

**Comment by yxxhero** [comment]
@mumoshu ok

**Pull request merged**
