### PR TITLE
Upgrade helm diff version

### PR DESCRIPTION
**Pull request by yxxhero**
Upgrade helm diff version

### CODE REVIEW

**Comment by yxxhero** [comment]
@mumoshu

**Comment by yxxhero** [comment]
waiting for 3.8.1?

**Comment by mumoshu** [comment]
@yxxhero As this is an opt-in feature, we can merge this first. I'll try to cut helm-diff 3.8.1 soon!

**Comment by yxxhero** [comment]
@mumoshu ok. Please approve. thanks.

**Review by mumoshu — APPROVED** [review]

**Pull request merged**
