### PR TITLE
rename HELMFILE_SKIP_INSECURE_TEMPLATE_FUNCTIONS to HELMFILE_SKIP_INSECURE_FEATURES

### PR DESCRIPTION
**Pull request by itscaro**
maybe it more succinct:

HELMFILE_DISABLE_INSECURE_FEATURES
HELMFILE_SKIP_INSECURE_FEATURES

### CODE REVIEW

**Comment by yxxhero** [comment]
@itscaro is it a breaking change?

**Comment by yxxhero** [comment]
@itscaro please fix conflicts.

**Comment by itscaro** [comment]
> @itscaro is it a breaking change?

Yes since I did no transition phase. Would you prefer transition phase? Don't know if it's used by many. The toggle disables the use of some dangerous function, these functions will return "" if the flag is set.

**Comment by yxxhero** [comment]
@mumoshu WDYT?

**Comment by mumoshu** [comment]
Hey! Honestly speaking, `HELMFILE_SKIP_INSECURE_FEATURES` doesn't make sense to me, as not all the insecure features can logically be "skipped". "Disable" sounds more like it would produce an error if you tried to use the disabled feature. "Skip" sounds more like it would make the feature noop, neither producing output nor error.

**Comment by itscaro** [comment]
I agree with @mumoshu that the new variable is less clear. But having two variables quite different makes it hard to remember.

Or another approach, I think of, is to implement `helmfile env` to list these variable? Maybe they are already listed elsewhere in CLI and I don't know.

**Comment by mumoshu** [comment]
@itscaro I hear you! Then can we instead enhance HELMFILE_DISABLE_INSECURE_FEATURES so that any insecure template functions return errors instead of being silently skipped? The current behavior of those functions being silently skipped is confusing anyway so perhaps we can deprecate and remove it in favor of the ability to not "skip" but "disable" insecure template functions?

**Comment by mumoshu** [comment]
In the Slack channel, @yxxhero pointed out to me that the HELMFILE_DISABLE_INSECURE_FEATURES enhancement might be a breaking change, which should be deferred until v1.0. But my take was that it's a "security" fix. HELMFILE_DISABLE_INSECURE_FEATURES should have disabled all the insecure features including template functions, but i didnt, so we fix it.

**Comment by mumoshu** [comment]
The removal of HELMFILE_SKIL_INSECURE_TEMPLATE_FUNCTIONS should be done in/after v1.0, although we can deprecate it in 0.x.

**Comment by itscaro** [comment]
HELMFILE_DISABLE_INSECURE_FEATURES does panic when using dangerous templates functions + remote FS

HELMFILE_SKIP_INSECURE_TEMMLATING_FUNCTIONS / HELMFILE_SKIP_INSECURE_FEATURES silently applies noop for templating functions and does not change anything about remote FS

Is my summary clear?

**Comment by mumoshu** [comment]
@itscaro I believe you're correct!
And I just realized that we already implemented HELMFILE_DISABLE_INSECURE_FEATURES  for insecure template functions correctly https://github.com/helmfile/helmfile/blob/2a18134986e6156e284001e91ec89d9ba2bba86e/pkg/tmpl/context_funcs.go#L83-L97

**Pull request closed without merging**
